### ISSUE TITLE
Corail

### ISSUE THREAD

**Issue by GuerreroCraft61** [gottsch/gottsch-minecraft-GottschCore#29]
Can you solve this problem, please: https://github.com/Corail31/tombstone_lite/issues/141
The Corail modder are very childish

**Comment by gottsch** [comment]
Unfortunately, I can not fix this issue. I have tried reasoning with this modder already, but as you said, he is very childish. He has specifically coded his mod to throw errors when _**any**_ of my mods are present. I have read the link, and i'm not going to get into the outright lies (or misunderstandings) that he is spreading, as ultimately, it is his word against mine.

**Comment by GuerreroCraft61** [comment]
ok :(

**Comment by GuerreroCraft61** [comment]
I tested change the mod id using source code, and it work, can I use it for personal use?

**Comment by gottsch** [comment]
Yes, you can do that.
