### ISSUE TITLE
No Gottschcore 2.0.5 for Forge

### ISSUE THREAD

**Issue by yorkmouse** [gottsch/gottsch-minecraft-GottschCore#56]
I wanted to try out your mod: https://modrinth.com/mod/dungeonblocks (1.19.2 Forge)
However it requires Gottschcore 2.0.5 which doesn't exist for forge. Or will it be released any time soon?

**Comment by gottsch** [comment]
Oh rats, I haven't updated modrinth with that version yet, but you can get it at curseforge -> https://www.curseforge.com/minecraft/mc-mods/gottschcore/files/all
