### ISSUE TITLE
Forge 1.19.3 requires GottschCore 2.1.0 

### ISSUE THREAD

**Issue by PrinceAllart** [gottsch/gottsch-minecraft-GottschCore#60]
Hello, I tried installing the forge mod Treasures2! but it says it requires 2.1.0 of GottschCore... however, 2.1.0 is Fabric only. Please update for forge or allow it to use the 2.0.5 ver of GottschCore.

Thank you

![2023-08-22 13_13_17-CurseForge](https://github.com/gottsch/gottsch-minecraft-GottschCore/assets/109120805/aa81b798-4073-4db1-bb41-5f429e92aed9)

**Comment by gottsch** [comment]
I forgot to upload 1.19.3 :(

Anyway, I just did. It should be available in a few minutes.
